fermitools/jobsub_lite

lib/tarfiles.py, templates/dag/dag.dag.condor.sub, templates/dataset_dag/dagbegin.cmd, templates/dataset_dag/dagend.cmd, templates/dataset_dag/dataset.dag.condor.sub, templates/simple/simple.cmd
Add role to template so that if we specify --role on the command line, that gets passed to condor JDF.
=> Added role to templates for JDFs that jobsub_submit generates

lib/condor.py
Looks for InDownTime classad for a schedd, and if 'True' will not choose that schedd
=> add InDownTime classad filter to schedd selection process

templates/dag/dag.dag.condor.sub, templates/dag/dagman_wrapper.sh, templates/dataset_dag/dagbegin.cmd, templates/dataset_dag/dagend.cmd, templates/simple/simple.sh
=> check for defined but None or blank

bin/condor_submit, bin/jobsub_cmd, bin/jobsub_submit, lib/condor.py, lib/creds.py, lib/dagnabbit.py, lib/fake_ifdh.py, lib/get_parser.py, lib/packages.py, lib/poms_wrap.py, lib/tarfiles.py, lib/utils.py
Type annotations on functions/args throughout.
=> first stab at type annotations

bin/condor_submit, bin/jobsub_cmd, bin/jobsub_submit, lib/condor.py, lib/creds.py, lib/dagnabbit.py, lib/fake_ifdh.py, lib/get_parser.py, lib/packages.py, lib/poms_wrap.py, lib/tarfiles.py, lib/utils.py
Just black formatting.  No actual changes.
=> black formatting

tests/job_scripts/rebuild_gen_cfg, tests/test_submit_wait_int.py
script to put data files in various SAM instances, test job submission with latest ifdh_version, etc.
=> Data for test jobs

.pylintrc, bin/condor_submit, bin/condor_submit_dag, bin/jobsub_cmd, bin/jobsub_submit, lib/condor.py, lib/creds.py, lib/dagnabbit.py, lib/fake_ifdh.py, lib/get_parser.py, lib/packages.py, lib/poms_wrap.py, lib/tarfiles.py, lib/utils.py
- Open calls done with "with" and encoding=
- f-strings instead of %s stuff throughout
- misc ... return ... else: reworks
- some things flagged out  with #pylint: comments
- long strings broken down all over.
=> Make pylint happy

lib/condor.py, lib/fake_ifdh.py
This change will make jobsub_lite only select the schedds in the pool where IsJobsubLite is set to "true".  It works in conjunction with the `--devserver` flag, so if that flag is specified, only jobsub_lite devservers are chosen, and if it is not, then only non-dev jobsub_lite schedds are chosen.
=> Use IsJobsubLite classad to select jobsub_lite schedds

templates/simple/simple.sh
=> Clearing problem environment variables

lib/get_parser.py
leaving underscore versions as well for backwards compatability.
=> adding dashed versions of all the underscored arguments,

bin/jobsub_cmd
=> Fix for issue#92

bin/decode_token.sh, lib/fake_ifdh.py
So, much like old jobsub takes default role from a proxy if present, this takes the default role from
a token in BEARER_TOKEN_FILE.
=> default role from token

bin/jobsub_cmd
make sure schedd from either -name schedd or @schedd ends up as _condor_CREDD_HOST
fixes issue #98
=> set credd in jobsub_cmd wrapper.

bin/decode_token.sh
fix for underscores/slashes stolen from httokendecode.
=> decode_token fix

lib/tarfiles.py
Fix for #113 -- try alternate host on retries.
=> first draft at fixing rcds failover

tests/test_jobsub_submit_unit.py, tests/test_utils_unit.py
Should have been in #115, but there you go...
=> cleanup tests

templates/dataset_dag/samend.sh
=> Have SAM_END use $SAM_PROJECT  like SAM_BEGIN does

lib/tarfiles.py, tests/test_tarfiles_unit.py
=> Dropbox fix

templates/simple/simple.sh
…and wait for the first one to show up
Second pull request on #134 
"This time Rocky, for sure!!!"
=> use INPUT_TAR_DIR_LOCAL for rcds unpacked tar directories, 

bin/jobsub_cmd, bin/jobsub_fetchlog, lib/get_parser.py, templates/simple/simple.cmd, tests/test_dagnabbit_unit.py
So after discussing it at the meeting yesterday, I thought "How hard could it be to make the output more like old jobsub_q?"
so here it goes...
The main code involved is the logic in turning it on and off, and a few bits of classadd expression here and there.
=> Jobsub q format fix

lib/tarfiles.py
=> fix #161 by making tarballs in current directory

bin/jobsub_cmd
don't goof up -better-analyze with formatting options / header.
=> fix for #166

templates/dataset_dag/dagbegin.cmd, templates/dataset_dag/dagend.cmd, templates/dataset_dag/dataset.dag, templates/dataset_dag/dataset.dag.condor.sub, templates/dataset_dag/returnOK.sh, tests/dagnabbit/dagTest2, tests/dagnabbit/dagTest3, tests/dagnabbit/dagTest4, tests/dagnabbit/dagTest5, tests/dagnabbit/dagTest6, tests/dagnabbit/dagTest7, tests/test_submit_wait_int.py
This is the fix for the issue Vito mentioned yesterday in the meeting; adding the POST actions in the dataset dags that just succeed.   Stole the items from old jobsub.
=> Dataset dag posts

bin/condor_submit, lib/get_parser.py
=> let JOBSUB_GROUP set GROUP in base parser, use everywhere

bin/jobsub_cmd, lib/get_parser.py
Fix for #172 and also making `jobsub_q -G fermilab mengel`  (or other usernames) work right.
=> more jobsub_q tweaks

lib/get_parser.py, man/man1/jobsub_submit.1
=> help text/manpage fixup

bin/jobsub_submit, lib/condor.py
=> get rid of globbing .dag files etc to avoid possible confusion from user files

lib/get_parser.py, tests/test_get_parser_unit.py
Ran unit tests, submitted jobs with each flag specified to make sure it works.
=> Added --apptainer-image and --no-apptainer flags

lib/get_parser.py, tests/test_get_parser_unit.py
Marc - could you please make sure I didn't mess anything up in the test_get_parser.py file?  I think I understood how it figures out the arguments, but a second pair of eyes on that bit especially would be very heflpul.
=> Add --onsite and --offsite-only flags

bin/jobsub_cmd
=> adding --user username flag do jobsub_q

bin/jobsub_submit, lib/get_parser.py, man/man1/jobsub_submit.1, tests/test_get_parser_unit.py
=> Project name

templates/dag/dag.dag.condor.sub, templates/dataset_dag/dagbegin.cmd, templates/dataset_dag/dagend.cmd, templates/dataset_dag/dataset.dag.condor.sub, templates/simple/simple.cmd, templates/simple/simple.sh
until we figure out authentication issue for production/POMS submisssion (kcron?)
=> sigh... turning weakened tokens back off 

bin/jobsub_history
Add a jobsub_history command, implemented with condor_history.
Did in the style of jobsub_q, so you can also use all the condor_history flags.
=> Add history

lib/utils.py
=> non-backslash check BEFORE the quote

lib/tarfiles.py, templates/simple/simple.sh
… and dropbox:, also fix for -f dropbox://file   This allso covers the symlink half of #223
=> fixes for compatability with old jobsub regarding tarfiles

lib/get_parser.py, man/man1/jobsub_submit.1, templates/simple/simple.sh
Documentation for change in #223, #224.
=> Updated --tar-file-name documentation with corrected behavior

libexec/build_jobsub_lite_release.README, libexec/build_jobsub_lite_release.sh
Just a basic release build script.  We can make this fancier as needed, but for now it works.
=> Added release build script and README to the repo

lib/tarfiles.py
=> Problem vito found fixed

lib/tarfiles.py
=> Token auth vs dot netrc

lib/tarfiles.py
=> it is /pnfs/GM2/... for gm2

lib/fake_ifdh.py, lib/tarfiles.py
Don't know how I missed this...  but this works much better now.
=> make directories for pnfs dropbox case

bin/jobsub_submit
As caught by @goodenou testing gm2 scripts...
=> SAM_PROJECT and SAM_PROJECT_NAME on --dataset-definiton

bin/jobsub_submit
=> revisit SAM_PROJECT/SAM_PROJECT_NAME

templates/simple/simple.sh
In case they're uploading a script...
=> make -f files executable

lib/tarfiles.py
Alternate fix from #267, but one we want to test more.
=> all_purpose tarfile file mode fixer

lib/get_parser.py, templates/simple/simple.sh
Trying to fix cmtconfig bits for Minerva specific setup...
=> minerva specific bits update

templates/simple/simple.sh
… to see if it avoids held jobs with hold reason 12
=> Try copying rather than linking simple.sh

tests/test_dagnabbit_unit.py, tests/test_tarfiles_unit.py, tests/test_unit.py
The past few PRs have actually broken some unit tests.  I take responsibility for that, since I reviewed most of those PRs, and should have run unit tests on those to catch it in advance.  This PR fixes all the errors I found in the unit tests up to this point.
=> Unit test fixes

bin/jobsub_cmd, bin/jobsub_submit
=> fix for #300

lib/dagnabbit.py
=> dropped quote

tests/dagnabbit/dagTestHS, tests/test_submit_wait_int.py
Avoid a repeat of DAGs failing due to a missed quote, etc.
=> test that should collapse dag files

lib/condor.py, tests/test_submit_wait_int.py
Quick stab at making dune global pool work again.  Limiting schedd's to ones that match our domain name. 
(This in theory could then work at bnl, as well... maybe?)
=> find schedds with collector.query() for DUNE global pool

bin/jobsub_cmd, lib/get_parser.py, tests/test_dagnabbit_unit.py, tests/test_get_parser_unit.py, tests/test_submit_wait_int.py
=> Sanitize --constraint flag before passing argument to condor

lib/condor.py
From my discussion with Nick... We can even up busy vs not busy schedds.
=> weight schedd selection by RecentDaemonCoreDutyCycle

lib/get_parser.py, templates/dataset_dag/dagbegin.cmd, templates/dataset_dag/dagend.cmd, templates/simple/simple.cmd, tests/test_get_parser_unit.py
…it messes up when we merge them in the DAG code
=> Do not make resource_provides list start with a blank string, 

lib/get_parser.py, lib/version.py, templates/dataset_dag/dagbegin.cmd, templates/dataset_dag/dagend.cmd, templates/simple/simple.cmd, tests/test_get_parser_unit.py
This is just to clean up the branch history.  I'm not entirely sure why github thinks that anything except for the config is different, but the final state of this looks right to me.
=> Merge 1.1.5 branch into master

tests/test_submit_wait_int.py
After switching to testing .out files, finding dag.out sambegin.out, etc. so had to adjust a little...
=> Test fix 0321

bin/jobsub_submit, lib/get_parser.py, lib/skip_checks.py, lib/tarfiles.py, templates/dag/dag.dag.condor.sub, templates/dataset_dag/dagbegin.cmd, templates/dataset_dag/dagend.cmd, templates/dataset_dag/dataset.dag.condor.sub, templates/maxconcurrent_dag/maxconcurrent.dag.condor.sub, templates/simple/simple.cmd, templates/simple/simple.sh, tests/test_get_parser_unit.py, tests/test_skip_checks.py, tests/test_tarfiles_unit.py
=> Added flag to skip checks to save time on submission end.  Implemented here for RCDS

lib/get_parser.py, man/man1/jobsub_submit.1
=> help message/manpage cleanup of --mail-* options

templates/dataset_dag/dagbegin.cmd, templates/dataset_dag/dagend.cmd
one-line change to a few templates.  fixes #357.
=> include DesiredOS in dag begin/end to make DecisionEngine happy

lib/get_parser.py, man/man1/jobsub_submit.1
Forgot to do this as a part of #324 .  Must have documentation for any new feature!
=> Updated man page for jobsub_submit to include --skip-check flag

lib/dagnabbit.py, lib/get_parser.py, templates/dag/dag.dag.condor.sub, templates/dataset_dag/dagbegin.cmd, templates/dataset_dag/dagend.cmd, templates/dataset_dag/dataset.dag.condor.sub, templates/maxconcurrent_dag/maxconcurrent.dag, templates/maxconcurrent_dag/maxconcurrent.dag.condor.sub, templates/simple/simple.cmd
Just a few missing template lines....
=> fixes #371, fixes #236

lib/condor.py
Closes #380 
Fix two KeyError issues that come up if we use condor_submit rather than jobsub_submit.
=> Fixed key reference errors in condor.py

lib/condor.py
=> redo of #384 on 1.2-series

bin/condor_submit, bin/condor_submit_dag, lib/get_parser.py, tests/test_submit_wait_int.py
Update condor_submit and condor_submit_dag wrappers to pass actual arg-parser args to get_schedd(). 
Also add a test of actually submitting with condor_submit.
=> Fix 380 for 1.2.2

bin/condor_submit, bin/condor_submit_dag, lib/get_parser.py, tests/test_submit_wait_int.py
Update calls to get_schedd to pass parsed args.  Add a condor_submit wrapper test.
=> Fix 380 for master

lib/condor.py
* turn off renaming if vault token is readonly (managed token)
* copy plain vault-token to vault-token-group_role before submitting if avaliable.
=> Managed token / readonly vault token changes

templates/simple/simple.sh
Add a redirect and in ifdh cp...
=> template lines for -L / --log-file

lib/fake_ifdh.py
Problem Lisa reported with chmod failing re-adding pnfs persistent file...
=> More pnfs fun

Makefile, lib/condor.py, lib/version.py
Redo of #413, with the config submodule issue conflict resolved.
=> 1.3.2 release

man/man1/jobsub_submit.1
=> Fixed --tar-file-name entry in jobsub_submit man page

lib/tarfiles.py
This is a redo of #397, which got all funky when I tried to rebase it...
=> clear mtime on -f dropbox: tarfile creation.

bin/jobsub_cmd, bin/jobsub_totals, tests/test_jobsub_totals.py
... by piping to a simple total script.
=> adding totals to jobsub_q default output

bin/jobsub_cmd
Add the needed extra clause to the if.
=> fix #411 -- non-jobsub_q jobsub_cmd errors

lib/utils.py
This was printing an error in jobsub_fetchlog --condor.
=> utils.cleanup() was failing if cache directory was already removed

lib/get_parser.py, templates/dataset_dag/dagbegin.cmd, templates/dataset_dag/dagend.cmd, templates/simple/simple.cmd
This matches jobsub_client behavior.
Closes #461 
Please do NOT merge this until #131 is merged.
=> Changed --append-condor-requirements to save repeated invocations into a list 

bin/decode_token.sh, bin/jobsub
It's pretty much more documentation than code, but here it is.
Closes #471
=> Adding a 'jobsub' command to list available commands

bin/jobsub_cleanup_cred
Tool for users who have hosey credentials stuck on the credds to clean them all out so they can resubmit.
=> Adding jobsub_cleanup_cred script

bin/jobsub_totals
=> fixes #516

.github/workflows/pylint.yaml, .pre-commit-config.yaml, lib/utils.py
=> Add pylint github action

lib/condor.py, lib/fake_ifdh.py, lib/submit_support.py, lib/transfer_sandbox.py
=> get rid of import cycle

lib/render_files.py, lib/tarfiles.py, lib/utils.py, tests/test_utils_unit.py
This is intended to fix #506, by checking with df / quota if we have enough space to:
* generate rendered condor submit files in submit directory
* copy/change permissions in tarfiles
* copy in executable to submit directory
and directly fail saying there isn't going to be enough space before actually running out.
=> Check if we have enough disk space at strategic points

lib/render_files.py, lib/tarfiles.py, lib/utils.py
Closes #532 
I had to change the function signatures of a few funcs to accept a verbose value.  Please let me know if you think this is too clunky.
=> Suppress quota and df output for verbose=0

man/man1/jobsub_submit.1
Thank you @vitodb for pointing this mistake in 1.7-rc1 out.
=> Update default singularity image to be EL9

templates/simple/simple.sh
Don't get stuck with no output files If the user requests a nonexistent ifdh version.
=> fallback to current ifdh

bin/condor_vault_storer, lib/condor.py, tests/test_condor_unit.py
Latest from @DrDaveD .   Implements #544 .
=> Updating condor_vault_storer

lib/token_mods.py, lib/utils.py
we make a copy of our token because the submission monkeys with it, but
we weren't cleaning it up...
=> cleanup copied tokens

templates/simple/simple.sh, tests/data/condor_submit_dag/simple.sh
Address issue #574
Extend the use of cvmfs_info function to osgstorage repos alongside opensciencegrid repos
For SBND and ICARUS check also SBN CVMFS repos
=> Update cvmfs_info function

Makefile, lib/version.py
This just updates the `master` branch to include the 1.10 version release.  It only changes the various version files.
=> Merge 1.10-release into master

templates/dataset_dag/sambegin.sh, templates/dataset_dag/samend.sh
Have sambegin.sh and samend.sh find ifdhc  via Spack, as the simple.sh wrapper does. 
Also add some ifdh log calls to sambegin.sh and samend.sh to facilitate debugging.
=> using Spack to find ifdh, and adding logging to sambegin.sh, samend.sh

templates/simple/simple.sh
Redo of #620 against 1.11 release
=> Fix IFDH_VERSION for 1.11 release
