lib/condor.py

Fixed typos in printed message to user about where to find stdout/err files

Fixed typos

---

bin/jobsub_cmd
bin/jobsub_q
lib/get_parser.py

Added a callback `argparse.Action` to get_parser so that any inheriting module will automatically store the value of args.group into the environment variable GROUP.
For the shell scripts (jobsub_cmd, jobsub_q), pull the group flag/value out of the args, store it in GROUP, and modify args so that condor doesn't complain about the -G/--group flag getting passed.

Store -G/--group value into environment variable GROUP

---

spec/jobsub_lite.spec

There were a few remnants in the spec file (__pycache__ files, byte-code files) that would only work if source code was run.  This change is to allow for building of the RPM in the case that tests were run on a different machine, and strips out the installation and inclusion of cached and byte-compiled files.

Changes to spec file to make it work with a vanilla development env

---

templates/dag/dagman_wrapper.sh
templates/dataset_dag/dagman_wrapper.sh
templates/dataset_dag/sambegin.sh
templates/dataset_dag/samend.sh
templates/simple/simple.sh

The wrapper scripts were not correctly using the value of the --role flag to modify the default paths for the environment variables `BEARER_TOKEN_FILE` and `BEARER_TOKEN`.  This PR fixes that (#30 )

Update wrapper script templates to support roles

---

templates/dag/dagman_wrapper.sh
templates/dataset_dag/dagman_wrapper.sh
templates/dataset_dag/sambegin.sh
templates/dataset_dag/samend.sh
templates/simple/simple.sh

Setting `BEARER_TOKEN` in the job environment is a potential security leak, exposing tokens in log files, etc. by the common practice to print the jobs environment for debugging. It's now set internally by ifdh v2_6_3 when a token file is discovered. Eventually gfal2 will support token discovery: https://its.cern.ch/jira/browse/DMC-1226.
Fixes #33

don't set BEARER_TOKEN in wrappers

---

spec/jobsub_lite.spec

When we installed beta9, I realized that we accidentally wiped out the /etc/condor files, and I had to restore them from saved backups.  This should fix that.

Marked /etc/condor files as %config(noreplace)

---

bin/jobsub_submit
lib/get_parser.py
templates/dataset_dag/dagbegin.cmd
templates/dataset_dag/dagend.cmd
templates/simple/simple.cmd
tests/test_get_parser_unit.py

This addresses #45.  It also changes the default behavior of jobs with regards to running in Singularity containers:
1. No flag:  job runs in `DEFAULT_SINGULARITY_IMAGE` (as specified in `get_parser.py`)
2. `--singularity-image`:  job runs in specified singularity container, if it exists.  If not, job will fail (this is similar to present condor behavior).
3. `--no-singularity`:  Do not specify any singularity image.  Job will run according to where it lands.  This might be in a singularity container, or it might not be.

All jobs default to running in fnal_wn SL7 singularity container.

---

bin/condor_submit
bin/condor_submit_dag
bin/jobsub_cmd
bin/jobsub_submit
lib/get_parser.py
lib/poms_wrap.py

Currently jobsub_submit and friends blow up with a cryptic error if -G isn't set (defaulting to $GROUP in the
environment).   This patch checks early for this and error's out with a more specific error.

-G group /  better errors

---

.pre-commit-config.yaml
README.md

This PR adds a minimal config to have the pre-commit.ci github action run our pre-commit checks.  The one thing I'm not happy about is that the pre-commit hooks autoupdate can't be turned off entirely - so I scheduled it to run quarterly, and open any PRs regarding those into a separate branch.  After we move off python3.6, this shouldn't be an issue anymore.

Code changes to enable pre-commit.ci github action.

---

lib/fake_ifdh.py
tests/test_fake_ifdh_unit.py

We agreed to use the variable GROUP exclusively in jobsub code to define the VO. I removed references to the other variables with the same meaning.

remove EXPERIMENT variable in favor of GROUP

---

tests/test_unit.py

Lisa's PR (#101 ) revealed that our tests were treating "resource_provides" like a string, rather than a list, which is what get_parser.py defines for the --resource-provides flag (see https://github.com/marcmengel/jobsub_lite/blob/master/lib/get_parser.py#L254).  That made this test (https://github.com/marcmengel/jobsub_lite/blob/master/tests/test_utils_unit.py#L61) fail.  Fixed that here.

Made value for "resource_provides" a list, like get_parser.py would return

---

bin/jobsub_fetchlog
bin/jobsub_transfer_data
lib/condor.py
lib/get_parser.py
spec/jobsub_lite.spec
tests/test_condor_unit.py
tests/test_submit_wait_int.py

This adds a new `jobsub_fetchlog` binary that queries schedd to determine what local path the sandbox files will be downloaded to, then downloads the files and puts them into an archive, optionally copying them to another directory as well. Uses `htcondor` python bindings.
This adds a `Job` class in `lib/condor` that parses job IDs and handles the condor interactions.  I haven't looked at using it in other places where job ids are parsed (like the `jobsub_cmd` wrapper).
Fixes #10

jobsub_fetchlog 

---

lib/fake_ifdh.py

This just makes sure to print the stdout from htgettoken, since under normal conditions, it's not that much output.
More importantly, the user needs to see the authentication URL if they're getting the token for the first time

Bugfix for htgettoken URL not showing up

---

tests/test_creds_unit.py
tests/test_packages_unit.py

This PR just adds a fixture to the `test_packages_unit` tests that sets up UPS, in case it's not already set up in the user's environment.  In a standard terminal/shell, a developer can just set up UPS/Spack, and then run the pytest command manually; but in an IDE like VSCode, PyCharm, etc., the environment for the native IDE testing functionality is often separate from the built-in terminal, and so simply sourcing a script won't work.  This change should ensure that no matter where a developer is running the tests from, as long as UPS is available, the unit tests should behave as expected.

Added fixture setup_ups to set up UPS in test environment

---

bin/condor_submit
lib/condor.py
lib/fake_ifdh.py
lib/tarfiles.py
spec/jobsub_lite.csh
spec/jobsub_lite.sh
tests/test_condor_unit.py
tests/test_submit_wait_int.py
tests/test_unit.py

This pull request moves all literal hostnames  into the config.d and spec subdirectories, so they can be
split out into a separate, private, Git repo.  Two of them, in the test code, are replaced by obfuscating
functions, which should still hide them from things that scan for hostnames, and will also give wrong/different
answers offsite.

Host cleanup part 1

---

lib/get_parser.py
templates/simple/simple.sh
tests/test_get_parser_unit.py

last tidbit for #119, #84 adding a command line option to not clear our list of bad environment variables in the wrapper.

make environment cleanup optional

---

bin/condor_submit
bin/condor_submit_dag
bin/jobsub_cmd
bin/jobsub_fetchlog
bin/jobsub_submit
lib/get_parser.py
tests/test_get_parser_unit.py

This pull request f1xes #122, and parts of #123, and a few other bits brought up by users, and improves
command-line backwards compatability on the non jobsub-submit wrappers.
You can now use --jobid=1234.0@schedd or 1234.0@schedd or -name schedd 1234.0 
interchangeably on all the commands that take jobid's. 
You can do any of jobsub_q --better-analyze or jobsub_q -better-analyze or condor_q -better-analyze,
ditto for -long / --long.
It also includes the condor_q --help info in jobsub_q --help, etc.

Arg handling and help fixup

---

lib/fake_ifdh.py
tests/test_fake_ifdh_unit.py

If X509_USER_PROXY is set, we assume the proxy should live there or should be generated there

If X509_USER_PROXY is set, we assume the proxy should live there - fix for kherner issue 

---

bin/jobsub_fetchlog

Right now if you get an error in transfer_data(), jobsub_fetchlog just exits without tarring up the (partial) results.
Modified to log the error and warn the user the transfer may be incomplete, but still tars/delivers the results we
did get.

handle incomplete transfers

---

lib/fake_ifdh.py

Added -vomslife attribute so that the generated proxies have voms extensions that are valid for 167 hours.

Make sure voms extension also has 167 hours for generated proxies at submission

---

templates/simple/simple.cmd

Not tested, but doesn't get much simpler.

JobsubCmd classad attribute needs to be a string

---

bin/jobsub_submit
lib/condor.py
templates/simple/simple.cmd

Add line in job JDF to tell condor schedd not to curtail lifetime of x509 proxy, along with a couple of verbose statements and small changes to increase readability.
Passed unit tests, and test laid out in #179.
This solves the first half of #179, but does not fix the issue with DAGs.  When #185 is completed, I will implement the same change to the DAG templates in a future PR.

Add line in job JDF to tell condor schedd not to curtail lifetime of x509 proxy

---

lib/condor.py

Avoid bugs like the one that affected 0.2 by using get() calls instead of straight key-accesses.

Change key access to get() calls where we may not have a var set from a caller

---

lib/fake_ifdh.py
lib/tarfiles.py
tests/test_tarfiles_unit.py

[from slack channel]
vito  11:48 AM
while doing some check for jobsub_lite ticket INC000001144465 [dropbox bug] it looks like if I want to transfer a file to the job I get different hash every time I use that file, so RCDS picks up a different CVMFS path each time, is this the expected behavior?
mengel [12:09 PM]
It's supposed to be based on the md5 hash of the tarfile... but that tickles a memory: https://unix.stackexchange.com/questions/438329/tar-produces-different-files-each-time
let me see if their workaround works here...
(i.e using gzip -n when compressing the repository to omit the timestamp)
Okay that works... thus this pull request, with a test!

tarfile hash repeatability fix

---

tests/test_condor_unit.py
tests/test_creds_unit.py
tests/test_dagnabbit_unit.py
tests/test_decode_token_unit.py
tests/test_fake_ifdh_unit.py
tests/test_get_parser_unit.py
tests/test_jobsub_submit_unit.py
tests/test_packages_unit.py
tests/test_submit_wait_int.py
tests/test_tarfiles_unit.py
tests/test_utils_unit.py

Added support for doing:
JOBSUB_TEST_INSTALLED=1 pytest
to test the installed version of jobsub, rather than the copy we're sitting in.

JOBSUB_TEST_INSTALLED environment flag

---

lib/get_parser.py
lib/utils.py
templates/dataset_dag/dagbegin.cmd
templates/dataset_dag/dagend.cmd
templates/simple/simple.cmd
tests/test_get_parser_unit.py
tests/test_utils_unit.py

There's a lot here.  This is a summary of the changes.
1.  --site now works
2. --site defaults to "", not None
3. --site is mutually exclusive with --onsite/--offsite flags
4. As described in #198, there is new logic on how --site, --onsite/offsite, and --resource-provides=usage_model is handled.  The summary is here:  https://github.com/marcmengel/jobsub_lite/issues/198#issuecomment-1363266689 .  We basically give precedence to --site, then --onsite/offsite, then --resource-provides=usage_model.
5. Changed templates to select site properly
I've requested all three of you to check this:
@goodenou: this reimplements the logic you had before, but slightly changed.  Please make sure it makes sense to you, both from a technical and as FIFE lead in terms of policy.
@retzkek: (3) above - does …

Fix --site flag

---

lib/utils.py

In jobsub_client, one needs to backslash quotes, etc. in  the --lines values.

draft of --line backslash compatability

---

bin/jobsub_cmd
bin/jobsub_fetchlog
bin/jobsub_submit
lib/get_parser.py
lib/version.py

I added arguments "--version" and ""support-email" to the list of base arguments so that folks can now submit a command such as "jobsub_fetchlog --version" and get the following output back "jobsub_lite version 0.3". The version is stored in lib/version.oy.

adding version and help email to jobsub_ arguments

---

bin/jobsub_submit
lib/utils.py

This is round 2 of addressing the compatability issue that Heidi brought up.  
In the old jobsub_client, the jobsub_submit arguments were sent over to the server, and
then the server ran a server-side jobsub_submit script locally, which involved running
another shell, and an extra eval-layer of substituting backslash-whatever. 
This happened to all of the command-line arguments, so here we do the whole of sys.argv.

do backslash-escape processing on all args, not just --lines

---

lib/utils.py

backwards compatability.
Small change in fix_units_... code.

allow short, medium, long for duration flags --timeout and --expected_lifetime

---

lib/dagnabbit.py
lib/utils.py

Fixes 
```
<serial>
<parallel>
jobsub_submit
<parallel>
...
</serial> 
```
in DAGS, as well as backslash/quoting in dag command lines.

fixes for Herb's DAG issues

---

templates/dag/dag.dag.condor.sub
templates/dataset_dag/dagbegin.cmd
templates/dataset_dag/dagend.cmd
templates/dataset_dag/dataset.dag.condor.sub
templates/simple/simple.cmd

@rlcee's testing with POMS showed that we neglected to lower-case the user-provided role in the templates.  We do when getting tokens, but then keep the original form for the templates.  This eventually prevents jobs from starting, as the condor_schedd looks for the credential in the form group_role.use.  If "role" is wrong, then the condor_schedd cannot find the credential, and thus the job never starts.  This can be seen in the ShadowLog.

Lower-case all instances of role in templates when being used for oauth specification

---

templates/dag/dagman_wrapper.sh
templates/dataset_dag/dagend.cmd
templates/dataset_dag/dagman_wrapper.sh
templates/dataset_dag/sambegin.sh
templates/dataset_dag/samend.sh
templates/simple/simple.sh

This is from @rlcee's issue he brought up today - I forgot to lowercase the roles in the wrapper script templates (I did for the job submission file templates).

Lowercase role for BEARER_TOKEN_FILE setting in wrapper scripts

---

lib/utils.py

Sanitize --lines "''" or --lines '""'

---

lib/fake_ifdh.py

Allow for a default role file to be read in that either the managed token service could push
or the user could add.   It is either:
`/tmp/jobsub_default_role_${GROUP}_$(id -u)`
or
`$HOME/.jobsub_default_role_${GROUP}_$(id -u)` 
and should contain the role (i.e. "Analysis" or "Production")

code to read a default role

---

lib/get_parser.py
man/man1/jobsub_submit.1

Noted that in example `-f /path/to/myfile`, `/path/to/myfile` must be grid-accessible via ifdh.

Added warning about grid-accessibility for -f argument

---

templates/dag/dag.dag.condor.sub
templates/dataset_dag/dagbegin.cmd
templates/dataset_dag/dagend.cmd
templates/dataset_dag/dataset.dag.condor.sub
templates/simple/simple.cmd
tests/test_condor_unit.py

Per Joe Boyd, we don't need to set +Owner anymore, that's an artifact of old jobsub, where everything was really submitted by rexbatch who was a superuser, and then setting +Owner made the job run as the original user...

remove +Owner lines from submit files

---

lib/get_parser.py

Fixes #262 
Unit tests pass.
Also, with the following jobsub_submit command:
```$ jobsub_submit -G fermilab -n file:///usr/bin/true```
We get the following request disk in the submit file:
```
$ grep -i disk  /home/sbhat/.cache/jobsub_lite/js_2023_02_03_035632_9fe6ea25-f37d-4135-9de8-72a5deec130d/simple.cmd 
request_disk = 36700160.0KB
```
So that works.

Changed disk default to 35GB to be inline with jobsub_client default

---

lib/creds.py
lib/get_parser.py
tests/test_creds_unit.py

We were reading the role in from the default role file, but not actually setting it in a way that the template could see.  This fixes that issue.

Set role in args dict from return value of fake_ifdh.getRole

---

lib/tarfiles.py

Mimic old jobsub and make -f drobpox: files world readable before tar-ing them up (then put the permissions back).

permissions fun

---

lib/utils.py
tests/test_utils_unit.py

This fixes INC000001146876 that @hgreenlee submitted in ServiceNow.  We correct the case of `ONSITE_SITE_NAME`, and make sure that all checks for `ONSITE_SITE_NAME` in the given `--site` flag are case-insensitive checks.  This way, if someone says `--site Fermigrid` or `--site FERMIGRID`, it gets corrected.  
Also added unit test for the latter.
Passed all unit tests, as well as the following submission tests:
`jobsub_submit -G mu2e --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC,OFFSITE --site=FermiGrid -n file:///usr/bin/printenv`
DESIRED_usage_model = "DEDICATED,OPPORTUNISTIC"
DESIRED_Sites="FermiGrid"
`jobsub_submit -G mu2e --onsite  --site=FermiGrid -n file:///usr/bin/printenv`
Not allowed - can only specify one of --site or --onsite
`jobsub_submit -G mu2e --onsite  -n …

Fix ONSITE_SITE_NAME case and make onsite --site check case-insensitive

---

lib/get_parser.py

Thanks to @kherner for pointing this out.
We were using an outdated value for our default.  This was the document, which has since been updated:
https://cdcvs.fnal.gov/redmine/projects/fife/wiki/Information_about_job_submission_to_OSG_sites

Change disk default to 10GB

---

templates/simple/simple.sh

As in old jobsub, and the help.   Not sure where JOBSUB_OUT came from...

CONDOR_DIR_xxx not JOBSUB_OUT_xxx environment variable

---

lib/fake_ifdh.py
lib/token_mods.py

This fixes the issue reported in RITM1639431, which you can reproduce by removing your bearer tokens and:
```
export PATH=/bin:/usr/bin:/usr/sbin
/opt/jobsub_lite/bin/jobsub_q 
```
which gives:
```
Attempting to get token from https://htvaultprod.fnal.gov:8200 ... succeeded
Storing bearer token in /tmp/bt_token_fermilab_Analysis_1733
decode_token.sh could not successfully extract the expiration time from token file /tmp/bt_token_fermilab_Analysis_1733. Please open a ticket to Distributed Computing Support if you need further assistance.
Traceback (most recent call last):
File "./jobsub_q", line 228, in <module>
main()
File "./jobsub_q", line 152, in main
os.environ["BEARER_TOKEN_FILE"] = fake_ifdh.getToken(role)
File "/home/mengel/jobsub_lite/lib/fake_ifdh.py", line 139, in getToken
if …
```

use full path for decode_token.sh

---

bin/jobsub_fetchlog
lib/condor.py

We (I) inadvertently left it out of the rewrite. condor_transfer_data will abide whatever the constraint is, we were forcing it to be the cluster.

add --partial argument to jobsub_fetchlog

---

templates/dag/dag.dag.condor.sub
templates/dataset_dag/dataset.dag.condor.sub
templates/maxconcurrent_dag/maxconcurrent.dag.condor.sub

These classad attributes were inadvertently left out of the DAGs, they're needed for jobview to find the log path on dcache.

add JobsubOutputURL and JobsubUUID to dag sub files

---

lib/fake_ifdh.py
lib/token_mods.py
tests/test_dagnabbit_unit.py

In #280 , we broke the very esoteric use case of a python script calling jobsub_submit after doing an `os.chdir`.  So we go back to the assumption that `decode_token.sh` is in the `PATH`, and add it in for the testing case.

Go back to the assumption that users have decode_token.sh on their PATH.  Added bin dir to PATH for testing

---

lib/utils.py
templates/simple/simple.sh

Transfer info was showing up at the top of stderr, which could confuse and anger users. Here they won't show up in the web logs at all, but could still be seen in the spool logs for debugging. Downside is if the job is violently killed such that the postscript functions don't get to run, they won't get transferred.
Also includes a couple comments regarding changing log output url and/or path for posterity.

Move cmd and script transfers to end of job

---

bin/condor_submit
bin/condor_submit_dag
bin/jobsub_fetchlog
bin/jobsub_history
lib/condor.py
lib/tarfiles.py
tests/test_tarfiles_unit.py

This fixes the tarball problems introduced with symlinks, adds LD_LIBRARY_PATH-proofing to rest of scripts in bin, and adds extra horizontal lines and whitespace to make the job_id  stand out.

Fixes to fixes

---

lib/utils.py
templates/simple/simple.cmd
tests/test_dagnabbit_unit.py

Yet another patch on the DAG-crunching, for when the count gets passed through into the wrapper script on the command arguments; where we need to convert the DAG/submit parameters to environment variables to use them.

dagman crunching patch for values ending up in the shell script

---

bin/jobsub_cmd
bin/jobsub_fetchlog
bin/jobsub_submit
lib/utils.py
lib/version.py

Closes #306 
We had different places setting the version, and we want as few of these as possible.  So now, the `lib/version.py` controls the version given throughout the library, and how it's printed.  This version variable is also printed in the templates, but with a slightly different form, as discussed in #306.  
So when the jobsub commands print the version, it looks like:
`jobsub_lite version 1.1.1`
And in the job templates, it looks like:
`JobsubClientVersion="jobsub_lite-v1.1.1"`
Note:  If approved, *DO NOT MERGE* until after 1.1.2 is deployed, on 2023-03-01.

Standardize version and support-email printing throughout code

---

bin/jobsub_submit
lib/dagnabbit.py
lib/tarfiles.py
templates/simple/simple.sh
tests/test_dagnabbit_unit.py

This addresses an issue Vito brought up, in #320, but also rubbed my nose in the fact that we weren't doing combinations of, say -e arguments on the command line versus the dagnabbit file properly -- if the dagnabbit file specified -e anything, that overrode *all* -e arguments from the command line, etc. when we should merge them.
Also switched the tarfile regeneration to make .bz2 files rather than .gz ones, as we had the random-hash due to current time showing up in those .gz tarballs, even with GZIP=-n set in the environment.  Now we get consistent hashes for tarfiles again.

Tarfile dag

---

templates/simple/simple.sh
tests/job_scripts/lookaround.sh
tests/test_submit_wait_int.py

add  pwd bits to template for CONDOR_OUT_BLAH  environment variables.
Add -d BLAH dir test to the test suite, and make sure lookaround.sh puts a file there and verify it gets copied out.

added -d tag dir test and check in integration tests

---

lib/get_parser.py
lib/utils.py
tests/test_utils_unit.py

As described in #330 , we establish the following convention here with regards to the `--singularity_image` flag and `--lines` flag with `SingularityImage` specified:
1.    If --singularity-image is specified and is NOT the default, use that.
2.   If --lines is given with a +SingularityImage classad, and that value is not the default, use that.
3.   Else, use the default.

Resolve --singularity-image and --lines with +SingularityImage conflicts

---

tests/data/singularity_image.json
tests/data/site_and_usagemodel.json
tests/test_utils_unit.py

Table-driven tests are great, but with this trend, we will see a our test files get huge.  So I moved the test cases for the biggest offender, `test_resolve_site_and_usage_model`, to their own data file.
I did not run entire unit test suite, but I made sure that all the tests in `test_utils_unit.py` pass.

Moved huge amount of site and usage model test cases to data file

---

bin/jobsub_cmd
bin/jobsub_fetchlog
bin/jobsub_history
bin/jobsub_submit

This is a second round on error cleanup; print stacktraces if verbose/debug is on.   Have to make the argument list global so we can check verbosity where we call main().

give stack traces if debug/verbose

---

templates/simple/simple.sh
tests/job_scripts/lookaround.sh
tests/test_submit_wait_int.py

Several groups using SL6 containers have been running into roadblocks using jobsub_lite;
the main underlying issue is that there is no token support to be had in the underlying
gfal-utilities, etc. on SL6.

Tokens do not work on SL6 containers, so don't set BEARER_TOKEN_FILE

---

bin/jobsub_fetchlog
templates/dataset_dag/dagbegin.cmd
templates/dataset_dag/dagend.cmd
templates/simple/simple.cmd

Finally it is here! Have `jobsub_fetchlog` download log archives from landscape (using token) instead of from condor. 
* Added `--condor` flag to use `condor_transfer_data` instead
*  Landscape doesn't support zip archives currently. We could add it, but do we really need to support zip? Could also untar and rezip on the client... :raised_eyebrow:
* Set LeaveJobInQueue to False so completed jobs leave queue immediately, but not for DAGMan jobs, since those logs are not currently transferred to dCache/landscape.
* https://github.com/marcmengel/jobsub_lite_config/pull/8
Fixes: #352

Fetchlog from landscape

---

tests/test_submit_wait_int.py

In testing the 1.2 release, two integration tests failed because they ran `jobsub_q`, which now prints out the default header, whether or not a job matching the constraint was found.  This broke both tests, because they check the length of the returned output to make sure it's zero.  This change was simply to force jobsub_q to pull down just the job information, since we're testing invalid constraints, and thus there should be no jobs to report on.

Update invalid constraint tests so they do not use default jobsub_q output format

---

tests/conftest.py
tests/test_condor_unit.py
tests/test_creds_unit.py
tests/test_fake_ifdh_unit.py
tests/test_tarfiles_unit.py
tests/test_utils_unit.py

This PR simply starts to clean up some of our unit tests by doing the following:
1.  Move shared test fixtures into `conftest.py`, which is the [recommended pytest way](https://docs.pytest.org/en/6.2.x/fixture.html#conftest-py-sharing-fixtures-across-multiple-files) of sharing fixtures across multiple test files
2.  Use the fixtures we have like `clear_x509_user_proxy` in older tests where we might have neglected to use the fixture, and are thus duplicating test code.
3. Formally parametrize some of the tests where we run the same test on multiple cases to take advantage of pytests's parametrization functionality (i.e. dynamically generating multiple named tests from a single test so all of the cases run, and we can clearly see which case failed).
Note:  I kept this in draft status so …

Tests cleanup

---

tests/test_unit.py

In preparing 1.2.1, I found that one unit test failed because we had failed to update test_unit vargs.  With this PR, all unit tests pass.

Fixed unit tests vargs to work with new generate-email-summary flag

---

bin/jobsub_cmd
tests/job_scripts/lookaround.sh
tests/test_submit_wait_int.py
tests/test_token_mods_unit.py

In jobsub_lite 1.2 and 1.2.1, if you list (or hold, or release, or ...)  specific jobs on specific schedd's, but you mention the schedd's more than once, we call each schedd again for each repetition, for example:  
```
jobsub_q -G fermilab  60440522.0@jobsub01.fnal.gov 60440943.0@jobsub01.fnal.gov 67113454.0@jobsub02.fnal.gov  67115375.0@jobsub02.fnal.gov
JOBSUBJOBID                             OWNER           SUBMITTED     RUNTIME   ST PRIO   SIZE  COMMAND
60440522.0@jobsub01.fnal.gov            mengel          04/07 15:55   0+00:05:23 C    0    0.0 dagman_wrapper.sh -p 0 -f -l . -Lockfi
60440943.0@jobsub01.fnal.gov            mengel          04/07 16:08   0+00:22:20 C    0    0.0 dagman_wrapper.sh -p 0 -f -l . -Lockfi
60440522.0@jobsub01.fnal.gov            mengel          04/07 15:55 …
```

make schedd's a set so we do not repeat them.

---

tests/test_get_parser_unit.py
tests/test_submit_wait_int.py

Working harder to use the right group / collector to fetch logs.
Dropping the test for repeating schedd's in jobsub_cmd,  as the setup to try to get 2 jobs on 2 schedd's  just doesn't seem to be reliable.

Cleanup integration tests

---

lib/tarfiles.py

Realized that a custom-made generator in the `TarfilePublisherHandler` does the same thing as `itertools.cycle`, so replaced that.  Also contains a bugfix where we used to reset the above-mentioned generator every API call rather than with every new CID.  So you could get something like:
```
for cid fermilab/12345
use dropbox_server_1 (fail)
use dropbox_server_2 (fail) 
use dropbox_server_2 (fail)
use dropbox_server_2 (fail)
use dropbox_server_2 (fail)
use dropbox_server_1 (fail)
use dropbox_server_2 (pass)
```
Rather than the intended:
```
for cid fermilab/12345
use dropbox_server_1 (fail)
use dropbox_server_2 (fail) 
use dropbox_server_2 (fail)
use dropbox_server_1 (fail)
use dropbox_server_2 (fail)
use dropbox_server_1 (fail)
use dropbox_server_1 (fail)
use dropbox_server_2 (pass)
``` …

Dropbox selector as cycle

---

lib/fake_ifdh.py
tests/test_submit_wait_int.py

Small tweak in fake_ifdh.py to keep it from getting confused by extra slashes, or passing them on to gfal-copy and confusing it.   Does not mess with other URL types, etc.

deal with extra slashes in, i.e. , dropbox:////some/place #396

---

bin/jobsub_cmd

Just a quick change I thought about after reviewing #405.  Since we always expect a list in `args_for_schedds`, rather than do a check for schedd membership in that dict, we can simply make it a default dict which will add the key automatically if it doesn't exist.
Tested this doesn't break anything (and still solves #370, like #405 did) with the following:
```
~/jobsub_lite/bin/jobsub_submit -G fermilab --debug -N 20 --devserver file:///usr/bin/sleep 300
~/jobsub_lite/bin/jobsub_q -G fermilab --devserver --jobid=11420.0@jobsubdevgpvm01.fnal.gov
~/jobsub_lite/bin/jobsub_rm -G fermilab --devserver --debug --jobid=11420.@jobsubdevgpvm01.fnal.gov
```

Made args_for_schedd into a defaultdict because we always expect list values

---

lib/condor.py

Do *not* copy `/tmp/vt_u$(id -u) ` to ` /tmp/vt_u($(id-u)_group-Role` because it confuses condor_vault_storer,
which uses the latter file to keep track of when it uploads to the credmon...

Do not try to be too helpful with vault tokens

---

lib/get_parser.py
lib/utils.py
tests/data/site_blacklist_bad.json
tests/data/site_blacklist_good.json
tests/test_utils_unit.py

Just a little idea I've had for a while - if we have `--blacklist` and `--site`, we should make sure those lists don't conflict.  jobsub_client used to do that and we never brought that (good) functionality over, so I've done it here.

Blacklist site checker

---

lib/skip_checks.py
lib/tarfiles.py
tests/test_tarfiles_unit.py

If user tries to use --tar-file-name with a file that is not a tar archive, raise error advising user to switch to -f flag instead

---

lib/tarfiles.py
lib/utils.py

This to avoid the problems of #417, or similarly, problems with two job submissions doing
`--tar-file-name tardir:///same/path`  from the same directory at the same time, we put the
process-id in the generated tarfile names.

put pid in tarfile names we create to avoid clashes

---

lib/condor.py
lib/get_parser.py
tests/test_get_parser_unit.py

Closes #421 
I also changed the `condor_status -schedd` code to use a jinja template, since the logic with this added feature was getting a bit tougher to parse.
Tested with no schedd specified, a couple of our real schedds, and a fake schedd.  Jobs were properly directed to the requested schedd, or the submission rejected in the case of the fake schedd.  All jobs (`sleep 300`) succeeded.
Also, ran all unit tests, which pass.

Add --schedd-for-testing flag

---

bin/jobsub_cmd

Allow multiple job ids separated by commas for --jobid

fixes #428

---

lib/condor.py
tests/test_condor_unit.py

Closes #367 
Along with fixing #367, I realized that for this, and possibly other cases, we're making multiple calls to the collector to get schedd info, where we really only need that once, since we don't retain state between executable runs.  For that reason, I also changed `get_schedd_list` to write to a global var, `__schedd_ads`, which is simply a dict of `schedd_name: schedd_ad`.  `get_schedd_list` then checks if this dictionary is populated before querying the collector.  If it does need to query the collector (and this can be forced via a new argument to the function), it will populate `__schedd_ads` as well.
Other functions inside the `condor.py` module can then also use this global variable to query schedd ads, which is what I use here to get the …

Store schedd ads in memory via global variable; give more user-friendly error message if MAX_PROCS_PER_SUBMISSION exceeded

---

bin/jobsub_cmd

note the cmd change 10 lines earlier...
cmd = cmd.replace("jobsub_", "condor_")
thus we need to check for cmd == "condor_q", not cmd == "jobsub_q"... sigh

fix the fix

---

templates/simple/simple.cmd

I think this resolves the issue VIto has been seeing with --maxConcurrent vs JOBSUBJOBSUBSECTION.

use our" is_dag" flag for JOBSUBJOBSUBSECTION choice

---

bin/jobsub_submit

Just a little logic check: if the --maxConcurrent value is greater than -N for how many jobs, just drop it. 
I'm doing this in jobsub_submit, just after we

implements #440

---

lib/tarfiles.py
tests/test_tarfiles_unit.py

So now we open the tarfile twice; once to checksum it, and the second time to get a fresh filehandle to pass as the data for requests.post for the upload.  This way we do not read the whole tarfile into memory, and cause memory size issues on large tarfiles.

Get rid of tarfile size memory limits by streaming upload

---

bin/jobsub_submit
lib/submit_support.py
tests/test_jobsub_submit_unit.py

Implementation of #451.    Created a new lib/submit_support.py with code that was already subroutines in jobsub_submit, and some more code split out to make the mainline more manageable.   Boundary between this code and utils.py  routines is unclear, should maybe have just made them utils1.py and utils2.py or something.
Note that this pull request attempts to make no changes to actual code; just *moves* it to another file and 
adds a few `def function_name(args, schedd_name): ` lines.   So wherever you see a block of code replaced by a subroutine call, you should later find that exact code in the body of that subroutine.
This probably leaves jobsub_submit with some imports it doesn't need any more, if folks are looking for more small improvements.

Refactor submit

---

lib/get_parser.py
man/man1/jobsub_submit.1

This was a request by @kutschke.  Rather than link to the fifewiki, I replicated that page on github, and link from the flags to the github wiki.  
Closes #427

Added file transfer documentation link to -f and --tar-file-name flags

---

lib/tarfiles.py

Checking the file size while we convert tarfiles, and raising an exception for files > 1G, which would fail later when and RCDS upload is attempted.

tarfile file-size checks

---

Makefile
lib/version.py

This will be a draft until the following PR:
https://github.com/fermitools/jobsub_lite_config/pull/18/
is merged.  We may need to update the config commit hash.

Bump version to 1.4.1

---

bin/jobsub_totals
tests/data/jq_out.txt
tests/test_jobsub_totals.py

Since the changes in #358 , the jobsub_q headings don't get piped through jobsub_totals anymore, but the totals script was still taking one off the number of lines for the total to account for the heading... 
Updated jobsub_totals, and took the heading out if its test-case data.

Fix totals again

---

bin/jobsub_cmd
bin/jobsub_fetchlog
bin/jobsub_submit
lib/tracing.py

log host and time to stderr if verbose/debug and to Jaeger trace, per #493

log host and time 

---

bin/jobsub_submit
lib/tarfiles.py

Basically, some of our cleanup calls weren't being made if we got exceptions at various points.
A couple of try:...finally: blocks should be the remedy.
Reviewers: look at the diffs ignoring whitespace, as blocks of text were indented for the try:finally: bits.

Cleanup tarfiles

---

Makefile

As it says above.  The idea is just to set the version, RC, and run `make` like normal.
To create a final release, as it says in the `Makefile`, set the RC to `0`.

Added capability to Makefile to create release candidates

---

lib/fake_ifdh.py
tests/conftest.py
tests/test_fake_ifdh_unit.py

Closes #507 
The main changes in this PR are as follows:
1.  If GROUP is not set in the environment, `getRole` calls `getExp` to get the group.  Previously, we would run into a `KeyError` in this case. 
2. Refactored `getRole` by extracting two functions that explain what we're checking to get the role:  `getRole_from_default_role_file` and `getRole_from_valid_token`.  This cleans up the `getRole` code and makes the logic much clearer.
3. Fixed bug in `getExp` where we didn't strip the newline character from the fallthrough `id -gn` case, and added a test for that case.
4. Lots of unit test refactoring in `test_fake_ifdh.py` to group the tests into classes, since we (rightly so) have multiple tests per `fake_ifdh.py` function.  I also parametrized tests where it made sense.

Don't assume we have GROUP set in the environment

---

lib/tarfiles.py
tests/test_tarfiles_unit.py

Closes #468 
This PR has a few changes to the way the `TarfilePublisherHandler` works:
1. `TarfilePublisherHandler` now accepts an argument `fixed_server` that determines whether or not it should switch servers between retries during a `pubapi_operation`.  The default value of this new argument is `False`, to keep in line with the old behavior.
2. There are new private and public methods to allow callers of `TarfilePublisherHandler` to switch fixed_server behavior on and off.
3. The function `tarfile_in_dropbox` uses (1) and (2) to make sure that the first `exists` call and subsequent `publish` call (if needed) go to the same RCDS server.  It then turns on server switching behavior for all subsequent `exists` calls.
4. The first time an RCDS operation fails, the `TarfilePublisherHandler` …

Improvements to TarfilePublisherHandler

---

lib/get_parser.py
lib/render_files.py
lib/skip_checks.py
lib/tarfiles.py
lib/utils.py
man/man1/jobsub_submit.1

Adds onto #521.  This PR introduces a new option to the `--skip-check` flag, called `disk_space`, that allows a user to run:
`jobsub_submit -G <group> --skip-check disk_space file:///path/to/executable`
That will disable the quota checks implemented in #521.  The default value for this setting is `False`, so the quota checks run by default.
This flag can also be run in combination with `--skip-check rcds`, so a user can skip either or both (or neither) of those checks.  I updated the helptext for `--skip-check` to reflect this.

Added skip-check option called disk_space to skip disk quota checking

---

.github/workflows/build-al9-pull-request.yaml
.github/workflows/build-al9-push.yaml
README.md

No actual added or removed code here.  I just split up the push/PR jobs into two separate github actions, to avoid confusion about which is supposed to run when, and so we can tell at a glance which ran.

Split build workflows into PR and push workflows

---

lib/fake_ifdh.py
tests/test_fake_ifdh_unit.py

Closes #531 
If a user runs `jobsub_submit -G uboone --role Production`, 1.6-rc1 would cause the submission to fail (using `--role production` was fine).  That would have been a breaking change based on the idea that jobsub should sanitize the case of the passed-in role.
This PR fixes that issue, and both `--role Production` and `--role  production` work now.

Checking token role and group should be case-insensitive

---

lib/get_parser.py
lib/utils.py
tests/data/singularity_image.json

Addresses almost all of #535.  The only thing left after this PR is finished is to then send out an announcement with the change.
Note to reviewers:
I did not change any of the DAG tests that specify using the sl7 image, because using the sl7 image is a valid use case.  The only test I changed is the one that looks for the default image, which should now be el9.

Changed DEFAULT_SINGULARITY_IMAGE to /cvmfs/singularity.opensciencegrid.org/fermilab/fnal-wn-el9:latest

---

lib/condor.py
lib/pool.py
tests/test_pool.py

This fixes the bug brought up in the discussions offline.
It also allows us to pass verbose mode to the underlying condor_vault_storer call made by condor_submit, either through the environment or via the verbose flag.
I ran all the unit and integration tests to validate these changes.

Make sure --global-pool doesn't clear the pre-existing environment

---

lib/condor.py
tests/test_condor_unit.py

In #551, we changed the behavior of how the `_condor_SEC_CREDENTIAL_STORER` environment variable was used.  Previously, the `condor.py:submit()` function would always coerce that environment variable to point to the jobsub_lite version of `condor_vault_storer`.  #551 changed that so that if `_condor_SEC_CREDENTIAL_STORER` was defined prior to submission, that setting was respected.  This broke POMS submissions, as POMS relies on jobsub's overriding whatever setting for `_condor_SEC_CREDENTIAL_STORER` that exists.
Originally, that portion of #551 was put in place to allow us to pass verbose and debug to the underlying `condor_vault_storer` commands for troubleshooting purposes.  This PR keeps that behavior by using the user-passed `--verbose/--debug` flags while restoring the previous …

This fixes a bug introduced in jobsub_lite 1.7

---

lib/fake_ifdh.py

Token-only launches were failing to copy sandbox files at launch... Needed 
BEARER_TOKEN set in the environment for gfal utilities.  Fixes #561

Stealing token compat from ifdh.cfg for fake_ifdh.py

---

tests/test_fake_ifdh_unit.py

Little testing bug I ran into when testing 1.8-rc1.

Delete test file if it's already there (for example if a previous test run didn't finish unlinking the file

---

tests/test_submit_wait_int.py

It needed some environment variables passed; not sure how they were getting through before, but they aren't lately (alma9 container? condor update?) .  Anyhow, I think the test works again now.

fix condor_submit_dag test

---

tests/test_fake_ifdh_unit.py

Some strings in the test should have had r-prefixes.

clear up escape warning in tests

---

lib/creds.py
lib/packages.py
lib/pool.py
lib/token_mods.py
tests/test_packages_unit.py

This fixes a bug that was introduced with the combination of #565 and #551.  Namely, for the `--global-pool` case, we were saving the environment before modifying the collector host, and then directly before submission, restoring it with `packages.orig_env()`.  
In this bug, since the original environment is saved during argument parsing, the credentials have not yet been gotten, and thus the `BEARER_TOKEN_FILE` and `X509_USER_PROXY` environment settings were wiped when `packages.orig_env()` is called in `condor.submit()`.
This PR fixes that bug, revealed in the testing of the 1.8-rc1 release.

When --global-pool flag is passed, make sure we save the BEARER_TOKEN_FILE and X509_USER_PROXY into the restored environment post-submission

---

lib/fake_ifdh.py
tests/test_fake_ifdh_unit.py

Fixes #570.
This PR also adds two new unit tests to check the new logic, as well as a minor bug fix for the existing getProxy tests themselves.
Note:  According to the docs:
- https://docs.python.org/3.7/library/subprocess.html#subprocess.run
- https://docs.python.org/3.7/library/subprocess.html#subprocess.CompletedProcess.check_returncode
there are two ways to check if a `subprocess.run()` call fails:
1.  Pass the `check=True` kwarg to the function, which will make it raise a `CalledProcessError` if the return code of the underlying subprocess is nonzero (i.e. `subprocess.run('exit 1', check=True)` will raise a `CalledProcessError`), and
2. If you don't want to immediately raise the error, set `check=False`, and then save the return value of `subprocess.run()` to a variable (e.g. …

If cigetcert fails for any reason, raise `PermissionError`

---

bin/jobsub_cleanup_cred

Closes #549 
This PR cleans up a lot of the code in `jobsub_cleanup_cred`.  The main changes are:
1. Adding support for non-Analysis roles, 
2. Adding error handling to the executable
3. Added a confirmation check before a user deletes credentials

Add support for non-Analysis users in jobsub_cleanup_cred

---

.github/workflows/build-al9-push.yaml

There are many security vulnerabilities in the AlmaLinux 9.3-minimal image (see https://hub.docker.com/layers/library/almalinux/9.3-minimal/images/sha256-16467e6b56cbd2e1f6621b2778003145e619fdbb8c5fed0dbfac851498d3719c?context=explore).  
This upgrades the workflow container to AlmaLinux 9.4.

Upgraded test container image from 9.3-minimal to 9.4-minimal

---

bin/jobsub_cmd
bin/jobsub_totals

Closes #501 
Sometime in the last few Condor releases, the classad `RemoteWallClockTime` stopped being populated in a job's classad while a job was running, and that broke our `jobsub_q`.  After consultation with the condor developers, this PR has the new implementation of calculating the job's cumulative run time.
The calculation for a running job is:  `(ServerTime - ShadowBday) + RemoteWallClockTime`.
For an idle, completed, or held job, the classad `RemoteWallClockTime` still works, and that's reflected in this PR.
This PR also includes a small tweak to the `jobsub_totals` script to improve performance; and a few comments to make clear what Condor expression corresponds to what column.

Fix RUNTIME for running jobs

---

tests/test_submit_wait_int.py

I accidentally broke the integration tests that depend on `fife_wrap` with #582.  This PR fixes that bug.

Put line continuation backslash back into fife_wrap tests

---

lib/get_parser.py
templates/simple/simple.cmd
tests/test_get_parser_unit.py
tests/test_jobsub_submit_unit.py

Closes #505
This new flag sets the following classads in the generated Job Definition File:
* `request_GPUs`  (for HTCondor:  See https://htcondor.readthedocs.io/en/latest/users-manual/submitting-a-job.html#jobs-that-require-gpus)
* `RequestGPUs` (For the OSG/GlideinWMS.  This flag has been in use for Fermilab's GWMS Frontends, and seems to be an alternate convention for jobs running on the OSG).
All unit and integration tests pass with this PR.

Add --gpu flag to submit jobs to GPU resources

---

bin/jobsub_fetchlog
lib/utils.py

In the course of investigating SNOW ticket INC000001183512, I found that there was a bug in how `jobsub_fetchlog` called `utils.cleanup` in the case that it was pulling logs from the condor schedd.  I fixed that bug here, as well as strengthening the error handling in the underlying `utils.cleanup` function.

Fix jobsub fetchlog verbose

---

Makefile

In the removal of SL7 artifacts from the build process, I forgot to remove the bit where we try to build the jobsub_lite-tracing-deps RPM.

Removed OS7 build of tracing-deps RPM

---

lib/condor.py
lib/get_parser.py

So this adds a --managed-token flag to jobsub_submit, which suppresses calling condor_vault_storer when we have
recently called it for this oauth_handle/token scope hash and this schedd.

draft of implementing #596

---

lib/condor.py
lib/get_parser.py
tests/test_get_parser_unit.py

The list of items that will be interpreted as False is any capitalization of the strings "0", "false", "no", and the empty string "".
This PR includes new tests to check for "falsey" values.

If JOBSUB_MANAGED_TOKEN is set to anything that implies False, set managed_token arg to False

---

lib/get_parser.py
tests/test_get_parser_unit.py

Closes #595 
This just adds a `difflib` check that drives a "Did you mean..." error message.  This PR includes accompanying tests.
For example:
```
$ bin/jobsub_submit -G fermilab --auth-methods token,proxy -n file:///bin/true                             
Submission files are in: /home/sbhat/.cache/jobsub_lite/js_2025_02_05_174257_7cbc693c-e519-483a-914d-1a381e3b796b
$ bin/jobsub_submit -G fermilab --auth-methods token -n file:///bin/true
Storing bearer token in /tmp/bt_token_fermilab_Analysis_10610
Submission files are in: /home/sbhat/.cache/jobsub_lite/js_2025_02_05_174223_fc719f07-5266-4aae-a97b-25cfb2b8daf8
$ bin/jobsub_submit -G fermilab --auth-methods tokens -n file:///bin/true                                  
Error: ValueError: The jobsub_lite infrastructure requires that the …
```

Add a "did you mean" clause for invalid but close to right auth methods

---

bin/jobsub
lib/get_parser.py
lib/mains/cmd.py
lib/mains/fetchlog.py
lib/mains/submit.py
lib/version.py
tests/test_get_parser_unit.py

This PR started out as a simple task to make the new subparser logic a bit clearer.  I ended up doing a bit of code cleanup at the same time, since unit tests were failing due to assumptions we can no longer make.  The changes, at a high level are as follows:
1. `lib/mains/*.py`: Most of the `jobsub_*_args` functions now accept an `argparse.Namespace` for better modularity.  However, we weren't checking for certain attributes (like `verbose`, etc.) to be set when executing different branches. This caused unit tests to fail; and I mostly substituted calls like `args.verbose` with `getattr(args, "verbose", 0)` (or some other sensible default given `lib/get_parser.py`)
2. `lib/get_parser.py`: Python's `argparse` library comes with a built-in `version` action. I simply use it in our parsers, …

Make subparsers clearer

---

bin/jobsub_submit
tests/test_get_parser_unit.py

This unit test was assuming that maxConcurrent could be anything.  Now that it's an int, the test broke.  This PR fixes it.
Also, we had forgotten to coerce maxConcurrent to 0 if we were not using a DAG in certain cases.

Fixed unit test after --maxConcurrent type restriction

---

lib/mains/cmd.py
templates/simple/simple.sh

It *should* activate the spack environment ending in $IFDH_VERSION, but instead 
the `echo &&` breaks desired behavior, and both spack environment activate  commands run 
and you end up with the last one...

Fix IFDH_VERSION behavior in job wrapper.

---

.github/workflows/pylint.yaml

Closes #628 
The `ubuntu-20.04` runner we were using in the pylint check is now deprecated.  This PR upgrades the version to `ubuntu-22.04`, and gets rid of the python3.6 check.

Upgraded runner version to ubuntu-24.04

---

.github/workflows/build-al9-push.yaml

As the title says.  The token used to checkout `jobsub_lite_config` now can ONLY do that.

Updated PAT to fine-grained token for better security

---

lib/tarfiles.py
tests/conftest.py
tests/test_tarfiles_unit.py

This PR fixes a bug where the following would fail, because we'd forgotten to ensure that a branch of the tarballs/dropbox code would obtain credentials:
```
jobsub_submit -G experiment --use-pnfs-dropbox -f dropbox://blahblah
```
It also starts to break out some of the test fixtures so we can get only tokens for our tests.
All tarfile unit tests pass with this PR (before, a number failed because of a failure to obtain a proxy after the CILogon CA shutdown).  There will be a number of other unit tests we'll have to update the same way to only get tokens.

Fix dash f pnfs bug
